apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    spec:
      organization: {{ .Values.organization }}
      securityContext:
        fsGroup: 1001
      group: {{ .Values.group }}
