# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: prometheus

# https://artifacthub.io/packages/helm/prometheus-community/prometheus?modal=values
prometheus:
  server:
    baseURL: prometheus.bnowak.com
    global:
      scrape_interval: 60s
      scrape_timeout: 10s
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - prometheus.bnowak.com
      tls:
        - hosts:
            - prometheus.bnowak.com
          secretName: prometheus-server-ingress-tls-cert
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: big-hostpath
    replicaCount: 1
    statefulSet:
      enabled: true
    retention: "365d"
  alertmanager:
    persistence:
      size: 5Gi
  prometheus-pushgateway:
    enabled: false
