# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace: grafana

# https://artifacthub.io/packages/helm/grafana/grafana?modal=values
grafana:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.nowak
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  persistence:
    enabled: true
    size: 50Gi
    storageClassName: microk8s-hostpath
  plugins:
  - grafana-clock-panel
  - grafana-simple-json-datasource
  - grafana-piechart-panel
  - grafana-worldmap-panel
  env:
    GF_ANALYTICS_REPORTING_ENABLED: "false"
