apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb-http-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: influxdb.nowak
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: influxdb
            port:
              number: 8086
  ingressClassName: nginx
