apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb-http-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: influxdb.nowak
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: influxdb
            port:
              number: 8086
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb-rpc-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: rpc.influxdb.nowak
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: influxdb
            port:
              number: 8088
  ingressClassName: nginx