configs:
  repositories:
    app-catalogue: 
      url: https://github.com/bartlomn/lab.app-catalogue
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    hosts:
    - argocd.bnowak.com
    tls:
    - hosts:
      - argocd.bnowak.com
      secretName: argocd-ingress-cert # < cert-manager will store the created certificate in this secret.
    https: true
