services:
  qbittorrent:
    image: hotio/qbittorrent:release-4.5.2
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1001
      UMASK: "002"
      TZ: "Etc/UTC"
    expose:
      - "8080"
    ports:
      - "8080"
    networks: 
      - vpn-net
    restart: unless-stopped
    volumes:
      - /hdd-raid/servarr-media/qbittorrent/config:/config:rw

