services:
  qbittorrent:
    image: hotio/qbittorrent:release-4.5.2
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1001
      UMASK: "002"
      TZ: "Etc/UTC"
    expose:
      - "8080"
    ports:
      - "8080"
    networks: 
      - vpn-net
    restart: unless-stopped
    volumes:
      - /hdd-raid/servarr-media/qbittorrent/config:/config
      - /hdd-raid/servarr-media/qbittorrent/downloads:/downloads
      - /hdd-raid/servarr-media/qbittorrent/watch:/watch

networks:
  vpn-net:
    driver: ipvlan
    driver_opts:
      parent: enp9s0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.83.20.9/24
          ip_range: 10.83.20.252/30
          gateway: 10.83.20.9

