apiVersion: v1
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      debug:
        addr: :5001
        prometheus:
          enabled: true
          path: /metrics
      headers:
        X-Content-Type-Options:
        - nosniff
        Access-Control-Allow-Origin:
        - http://dockerregistryui.nowak
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: {{ .Values.namespace }}
