# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: ingress-nginx

ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    admissionWebhooks:
      certManager:
        enabled: true
        admissionCert:
          duration: "1y"
          issuerRef:
            name: selfsigned-cluster-issuer
            kind: ClusterIssuer
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
          prometheus.io/scheme: http
  defaultBackend:
    enabled: true


# https://artifacthub.io/packages/helm/nginx/nginx-ingress/0.16.2?modal=values
# nginx-ingress:
#   controller:
#     enableCertManager: true
#     setAsDefaultIngress: true
#     enableTLSPassthrough: true
#     enableSnippets: true
#     healthStatus: true
#     healthStatusURI: "/nginx-health"
#     service:
#       type: LoadBalancer
#     serviceMonitor:
#       create: false
#       name: nginx-ingress
#     enableLatencyMetrics: true
#     disableIPV6: true
#     config:
#       entries:
#         log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $grpc_status $body_bytes_sent "$http_referer"  "$http_user_agent" "$http_x_forwarded_for" "$resource_name" "$resource_type" "$resource_namespace" "$service"'
#   prometheus:
#     create: true
#     port: 9113