# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: nginx-ingress

# https://artifacthub.io/packages/helm/nginx/nginx-ingress/0.16.2?modal=values
nginx-ingress:
  controller:
    setAsDefaultIngress: true
    enableTLSPassthrough: true
    enableSnippets: true
    healthStatus: true
    healthStatusURI: "/nginx-health"
    service:
      type: ClusterIP
    serviceMonitor:
      create: true
    pod:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: http
    enableLatencyMetrics: true
    disableIPV6: true
  prometheus:
    create: true
    port: 9113