# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: ingress-nginx

# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=values
ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    admissionWebhooks:
      certManager:
        enabled: true
        admissionCert:
          issuerRef:
            name: selfsigned-cluster-issuer
            kind: ClusterIssuer
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
          prometheus.io/scheme: http
  defaultBackend:
    enabled: true

