# Default values for argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd:
  configs:
    repositories:
      app-catalogue: 
        url: https://github.com/bartlomn/lab.app-catalogue

  dex:
    enabled: false

  server:
    extensions:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingressClassName: nginx
      hosts:
      - argocd.bnowak.com
      tls:
      - hosts:
        - argocd.bnowak.com
        secretName: argocd-ingress-cert
      https: true
