# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: wordpress

# https://artifacthub.io/packages/helm/bitnami/wordpress?modal=values
wordpress:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    pathType: Prefix
    hostname: wordpress.nowak
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls: true
  persistence:
    storageClass: microk8s-hostpath
    size: 10Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: wordpress
  mariadb:
    enabled: true
    primary:
      persistence:
        storageClass: microk8s-hostpath
        size: 10Gi