# Default values for servarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: servarr

prowlarr:
  global:
    # -- Set an override for the prefix of the fullname
    nameOverride: prowlarr
  
  controller:
    # -- enable the controller.
    enabled: true
    # -- Set the controller type.
    # Valid options are deployment, daemonset, statefulset or cronjob
    type: deployment

  image:
    # -- image repository
    repository: linuxserver/prowlarr
    # -- image tag
    tag: latest
    # -- image pull policy
    pullPolicy: IfNotPresent

  env:
    PUID: 1000
    PGID: 1000
    TZ: "Etc/UTC"

  # -- Configure the services for the chart here.
  # Additional services can be added by adding a dictionary key similar to the 'main' service.
  # @default -- See below
  service:
    main:
      # -- Enables or disables the service
      enabled: true
      # -- Configure the Service port information here.
      # Additional ports can be added by adding a dictionary key similar to the 'http' service.
      # @default -- See below
      ports:
        http:
          # -- Enables or disables the port
          enabled: true

          # -- Make this the primary port (used in probes, notes, etc...)
          # If there is more than 1 service, make sure that only 1 port is marked as primary.
          primary: true

          # -- The port number
          port: 9696

  # -- Configure persistence for the chart here.
  # Additional items can be added by adding a dictionary key similar to the 'config' key.
  # [[ref]](https://bjw-s.github.io/helm-charts/docs/common-library/common-library-storage)
  # @default -- See below
  persistence:
    # -- Default persistence for configuration files.
    # @default -- See below
    config:
      # -- Enables or disables the persistence item
      enabled: true
      storageClass: ssd-hostpath
      size: 5Gi

  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.152.183.10
      - 10.83.19.11
    searches:
      - servarr.svc.cluster.local
      - svc.cluster.local
      - cluster.local
      - bnowak.com
    options:
      - name: ndots
        value: "5"


# based on
# https://raw.githubusercontent.com/ishioni/homelab-ops/master/cluster/apps/media/transmission/helmrelease.yaml
# transmission:
#   global:
#     nameOverride: transmission
#   image:
#     repository: linuxserver/transmission
#     tag: "4.0.2"
#   controller:
#     type: deployment
#     revisionHistoryLimit: 2
#   env:
#     PUID: 1000
#     PGID: 1000
#     TZ: "Etc/UTC"
#     PEERPORT: 51413
#   dnsPolicy: "None"
#   dnsConfig:
#     nameservers:
#       - 1.1.1.1
#     options:
#       - name: ndots
#         value: "5"
#   probes:
#     liveness:
#       spec:
#         timeoutSeconds: 30
#     readiness:
#       spec:
#         timeoutSeconds: 30
#   service:
#     main:
#       ports:
#         http:
#           port: 9091
#     utptcp:
#       enabled: true
#       type: NodePort
#       ports:
#         utptcp:
#           enabled: true
#           # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#           nodePort: 31413
#           protocol: TCP
#           targetPort: 51413
#           port: 51413
#     utpudp:
#       enabled: true
#       type: NodePort
#       ports:
#         utpudp:
#           enabled: true
#           # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#           nodePort: 31414
#           protocol: UDP
#           targetPort: 51413
#           port: 51413
#   persistence:
#     config:
#       enabled: true
#       mountPath: "/config"
#       type: emptyDir
#     downloads:
#       enabled: true
#       mountPath: "/downloads"
#       type: emptyDir
#     watch:
#       enabled: true
#       mountPath: "/watch"
#       type: emptyDir
#       # existingClaim: servarr-media
#       # subPath: transmission
#   # volumeClaimTemplates:
#   #   - name: config
#   #     mountPath: /config
#       # storageClass: ssd-hostpath
#       # accessMode: ReadWriteOnce
#       # size: 100Mi
#   ingress:
#     main:
#       enabled: false
#       # ingressClassName: nginx
#       # annotations:
#       #   cert-manager.io/cluster-issuer: letsencrypt-prod
#       # hosts:
#       #   - host: transmission.bnowak.com
#       #     paths:
#       #       - path: /
#       #         pathType: Prefix
#       # tls:
#       # - hosts:
#       #   - transmission.bnowak.com
#       #   secretName: transmission-ingress-cert
