# Default values for servarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: servarr

# based on
# https://raw.githubusercontent.com/ishioni/homelab-ops/master/cluster/apps/media/transmission/helmrelease.yaml
transmission:
  global:
    nameOverride: transmission
  image:
    repository: hotio/qbittorrent
    tag: "release-4.5.2"
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
  controller:
    type: deployment
  env:
    PUID: 1000
    PGID: 1000
    UMASK: 002
    TZ: "Etc/UTC"
    PEERPORT: 51413
  probes:
    liveness:
      spec:
        timeoutSeconds: 30
    readiness:
      spec:
        timeoutSeconds: 30
  service:
    main:
      ports:
        http:
          port: 8080
    # utptcp:
    #   enabled: true
    #   type: ClusterIP
      # type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: transmission
      #   metallb.universe.tf/loadBalancerIPs: 10.83.20.202
      # externalTrafficPolicy: Local
      # ports:
      #   utptcp:
      #     enabled: true
      #     port: 51413
      #     protocol: TCP
      #     targetPort: 51413
    # utpudp:
    #   enabled: true
    #   type: ClusterIP
    #   # type: LoadBalancer
    #   # annotations:
    #   #   metallb.universe.tf/allow-shared-ip: transmission
    #   #   metallb.universe.tf/loadBalancerIPs: 10.83.20.202
    #   # externalTrafficPolicy: Local
    #   ports:
    #     utpudp:
    #       enabled: true
    #       port: 51413
    #       protocol: UDP
    #       targetPort: 51413
  persistence:
    config:
      enabled: true
      mountPath: "/config"
      type: emptyDir
    # downloads:
    #   enabled: true
    #   mountPath: "/downloads"
    #   type: emptyDir
    # watch:
    #   enabled: true
    #   mountPath: "/watch"
    #   type: emptyDir
      # existingClaim: servarr-media
      # subPath: transmission
  # volumeClaimTemplates:
  #   - name: config
  #     mountPath: /config
      # storageClass: ssd-hostpath
      # accessMode: ReadWriteOnce
      # size: 100Mi
  ingress:
    main:
      enabled: false
      # ingressClassName: nginx
      # annotations:
      #   cert-manager.io/cluster-issuer: letsencrypt-prod
      # hosts:
      #   - host: transmission.bnowak.com
      #     paths:
      #       - path: /
      #         pathType: Prefix
      # tls:
      # - hosts:
      #   - transmission.bnowak.com
      #   secretName: transmission-ingress-cert
