# Default values for servarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: servarr

# based on
# https://raw.githubusercontent.com/ishioni/homelab-ops/master/cluster/apps/media/transmission/helmrelease.yaml
app-template:
  global:
    nameOverride: transmission
  image:
    repository: ghcr.io/onedr0p/transmission
    tag: "3.00"
  podSecurityContext:
    runAsUser: 1003
    runAsGroup: 2000
    fsGroup: 2000
  controller:
    type: statefulset
  env:
    TZ: UTC
    TRANSMISSION__BLOCKLIST_URL: "https://mirror.codebucket.de/transmission/blocklist.p2p.gz"
    TRANSMISSION__DOWNLOAD_DIR: "/downloads"
    TRANSMISSION__INCOMPLETE_DIR_ENABLED: false
    TRANSMISSION__RATIO_LIMIT: 1
    TRANSMISSION__RATIO_LIMIT_ENABLED: true
    TRANSMISSION__SPEED_LIMIT_UP_ENABLED: true
    TRANSMISSION__SPEED_LIMIT_UP: 2048
    TRANSMISSION__UMASK: 7
    TRANSMISSION__WEB_HOME: "/app/web"
    TRANSMISSION__RPC_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: transmission-rpc
          key: rpc-password
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.1.1.1
    options:
      - name: ndots
        value: "5"
  probes:
    liveness:
      spec:
        timeoutSeconds: 30
    readiness:
      spec:
        timeoutSeconds: 30
  service:
    main:
      ports:
        http:
          port: 9091
    utptcp:
      enabled: true
      nameOverride: transmission-utptcp
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: transmission
        metallb.universe.tf/loadBalancerIPs: 10.83.20.202
      externalTrafficPolicy: Local
      ports:
        utptcp:
          enabled: true
          port: 51413
          protocol: TCP
          targetPort: 51413
    utpudp:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: transmission
        metallb.universe.tf/loadBalancerIPs: 10.83.20.202
      externalTrafficPolicy: Local
      ports:
        utpudp:
          enabled: true
          port: 51413
          protocol: UDP
          targetPort: 51413
  persistence:
    downloads:
      enabled: true
      existingClaim: servarr-media
      mountPath: "/downloads"
      subPath: transmission
  volumeClaimTemplates:
    - name: config
      mountPath: /config
      storageClass: ssd-hostpath
      accessMode: ReadWriteOnce
      size: 100Mi
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: transmission.bnowak.com
          paths:
            - path: /
              pathType: Prefix
      tls:
      - hosts:
        - transmission.bnowak.com
        secretName: transmission-ingress-cert
