---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-media
spec:
  capacity:
    storage: 2000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-media
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: hdd-hostpath
  volumeMode: Filesystem
  volumeName: servarr-media