apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-media
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: hdd-hostpath
  volumeMode: Filesystem
  volumeName: servarr-media