apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /home/hostpath-pvs
volumeBindingMode: WaitForFirstConsumer