# https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: observability-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: lab.local.lan
  share: /ssd-raid/nfs-share
  subDir: observability
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - hard
  - nfsvers=4.1
