# Default values for cockroachdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: cockroachdb

# https://artifacthub.io/packages/helm/cockroachdb/cockroachdb?modal=values
cockroachdb:
  conf:
    locality: planet=earth,country=pl,location=offfice,node=lab
  statefulset:
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - cockroachdb.nowak
    tls:
    - hosts:
      - cockroachdb.nowak
      secretName: cockroachdb-ingress-cert
  storage:
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: ssd-hostpath
  tls:
    enabled: false
    certs:
      selfSigner:
        enabled: false
